// ─── Shared careers data ─────────────────────────────────────────────────────
// Single source of truth for all role data, used by CareersPage and CareerDetailPage.

export const DEPT_COLORS = {
  Design: 'bg-violet-50 text-violet-700',
  Growth: 'bg-emerald-50 text-emerald-700',
  Marketing: 'bg-blue-50 text-blue-700',
  Sales: 'bg-orange-50 text-orange-700',
};

export const MODE_COLORS = {
  Remote: 'bg-emerald-50 text-emerald-700 border-emerald-100',
  Hybrid: 'bg-blue-50 text-blue-700 border-blue-100',
  Onsite: 'bg-orange-50 text-orange-700 border-orange-100',
};

export const ROLE_TOOLS = {
  Design: ['Figma', 'Adobe CC', 'After Effects', 'Notion', 'Slack'],
  Growth: ['HubSpot', 'Notion', 'Google Analytics', 'Slack', 'Linear'],
  Marketing: ['Notion', 'Google Workspace', 'SEMrush', 'Slack', 'Canva'],
  Sales: ['HubSpot CRM', 'Notion', 'Google Workspace', 'Slack', 'LinkedIn Sales Nav'],
};

export const HIRING_STEPS = [
  { step: '01', title: 'Application Review', desc: 'We review every application within 5 business days.' },
  { step: '02', title: 'Intro Call', desc: '20-minute call with the hiring manager to align on fit and expectations.' },
  { step: '03', title: 'Skills / Strategy Round', desc: 'A focused assessment — portfolio review, case study, or live task depending on the role.' },
  { step: '04', title: 'Leadership Round', desc: 'Final conversation with a founder or department head.' },
  { step: '05', title: 'Offer', desc: 'Fast turnaround. We move quickly for the right people.' },
];

export const ROLES = [
  {
    id: 'creative-director',
    title: 'Creative Director',
    dept: 'Design',
    type: 'Full Time',
    mode: 'Hybrid',
    location: 'Bangalore',
    salary: '₹9L – ₹12L / yr',
    tagline: "Lead iFranchise's visual ecosystem and brand creative direction.",
    reportsTo: 'Head of Brand & Creative',
    experience: '5+ Years',
    openings: '1',
    joining: 'Immediate / 30 Days',
    rounds: '3 Rounds',
    whyJoin: "At iFranchise, the Creative Director role is not a support function — it's a founding-level creative seat. You will shape how an entire category of franchise brands is perceived across India. Your work will be seen by thousands of investors, entrepreneurs, and brand partners every month.",
    about: 'We are looking for a Creative Director to own the visual identity of iFranchise across all touchpoints — digital, print, and motion. You will set the creative standard, mentor the design team, and collaborate directly with founders on brand strategy.',
    responsibilities: [
      'Define and evolve the iFranchise visual identity and design system',
      'Lead a team of designers and motion artists across projects',
      'Collaborate with marketing, product, and growth teams on campaigns',
      'Own brand guidelines, typography, color, and motion standards',
      'Review and approve all outgoing creative assets',
      'Present creative concepts to leadership and stakeholders',
    ],
    requirements: [
      '5+ years of experience in creative direction or senior design roles',
      'Strong portfolio demonstrating brand identity and digital design',
      'Proficiency in Figma, Adobe Creative Suite, and motion tools',
      'Experience leading and mentoring design teams',
      'Excellent communication and presentation skills',
      'Startup or agency background preferred',
    ],
  },
  {
    id: 'motion-designer',
    title: 'Motion Designer',
    dept: 'Design',
    type: 'Full Time',
    mode: 'Remote',
    location: 'India',
    salary: '₹6L – ₹9L / yr',
    tagline: 'Bring the iFranchise brand to life through world-class motion and animation.',
    reportsTo: 'Creative Director',
    experience: '2–4 Years',
    openings: '1',
    joining: 'Immediate / 30 Days',
    rounds: '3 Rounds',
    whyJoin: "Motion at iFranchise is not an afterthought. We believe animation and motion are core to how premium brands communicate. You'll have creative freedom, a supportive team, and the opportunity to build a motion language from the ground up.",
    about: 'As a Motion Designer at iFranchise, you will create compelling animations, video content, and interactive motion experiences that elevate our brand across social, web, and pitch decks. You will work closely with the Creative Director and content team.',
    responsibilities: [
      'Design and produce motion graphics for social media, web, and presentations',
      'Create animated explainer videos and brand reels',
      'Collaborate with the design team on UI micro-interactions',
      'Maintain consistency with brand motion guidelines',
      'Deliver assets optimized for multiple platforms and formats',
    ],
    requirements: [
      '2+ years of motion design or animation experience',
      'Proficiency in After Effects, Lottie, and Figma',
      'Strong understanding of timing, easing, and visual storytelling',
      'Portfolio with diverse motion work across digital formats',
      'Ability to work independently in a remote-first environment',
    ],
  },
  {
    id: 'franchise-growth-strategist',
    title: 'Franchise Growth Strategist',
    dept: 'Growth',
    type: 'Full Time',
    mode: 'Onsite',
    location: 'Bangalore',
    salary: '₹7L – ₹10L / yr',
    tagline: 'Drive franchise expansion strategy and brand partner growth across India.',
    reportsTo: 'Head of Expansion',
    experience: '2–4 Years',
    openings: '2',
    joining: 'Immediate',
    rounds: '3 Rounds',
    whyJoin: "This role sits at the intersection of strategy and execution. You'll work directly with founders, have access to real market data, and see the direct impact of your work as brands scale nationally through iFranchise.",
    about: 'The Franchise Growth Strategist will own the end-to-end growth pipeline for franchise brand partnerships. You will identify expansion opportunities, build relationships with franchise brands, and develop go-to-market strategies that drive platform growth.',
    responsibilities: [
      'Identify and onboard new franchise brands to the iFranchise marketplace',
      'Develop and execute growth strategies for existing brand partners',
      'Analyze market data to identify high-potential franchise categories',
      'Build and maintain relationships with franchise decision-makers',
      'Collaborate with marketing on lead generation campaigns',
      'Report on growth KPIs and pipeline metrics to leadership',
    ],
    requirements: [
      '3+ years in business development, growth, or franchise consulting',
      'Strong understanding of the Indian franchise market',
      'Excellent relationship-building and negotiation skills',
      'Data-driven mindset with experience in CRM tools',
      'Willingness to travel for brand meetings and events',
    ],
  },
  {
    id: 'ui-ux-designer',
    title: 'UI/UX Designer',
    dept: 'Design',
    type: 'Full Time',
    mode: 'Hybrid',
    location: 'Bangalore',
    salary: '₹6L – ₹9L / yr',
    tagline: 'Design intuitive, premium digital experiences for the iFranchise platform.',
    reportsTo: 'Head of Brand & Creative',
    experience: '2–4 Years',
    openings: '1',
    joining: 'Immediate / 30 Days',
    rounds: '3 Rounds',
    whyJoin: "You'll be designing for a platform that thousands of entrepreneurs use to make life-changing investment decisions. The design quality here directly affects trust, conversion, and brand perception — your work will matter.",
    about: 'We are hiring a UI/UX Designer to craft beautiful, functional interfaces for the iFranchise web platform and marketing pages. You will work closely with the product and engineering teams to translate user needs into elegant design solutions.',
    responsibilities: [
      'Design user flows, wireframes, and high-fidelity prototypes in Figma',
      'Conduct user research and usability testing to inform design decisions',
      'Maintain and evolve the iFranchise design system',
      'Collaborate with developers to ensure pixel-perfect implementation',
      'Design landing pages, dashboards, and onboarding experiences',
    ],
    requirements: [
      '2+ years of UI/UX design experience for web or mobile products',
      'Expert-level Figma skills with a strong portfolio',
      'Understanding of accessibility standards and responsive design',
      'Experience working in agile product teams',
      'Strong visual design sensibility and attention to detail',
    ],
  },
  {
    id: 'content-strategist',
    title: 'Content Strategist',
    dept: 'Marketing',
    type: 'Full Time',
    mode: 'Remote',
    location: 'India',
    salary: '₹5L – ₹8L / yr',
    tagline: 'Build the editorial voice and content engine that powers iFranchise growth.',
    reportsTo: 'Head of Marketing',
    experience: '2–4 Years',
    openings: '1',
    joining: 'Immediate / 30 Days',
    rounds: '3 Rounds',
    whyJoin: "iFranchise is building the definitive content resource for franchise growth in India. As Content Strategist, you'll own that narrative — from SEO to thought leadership to brand storytelling.",
    about: "The Content Strategist will own iFranchise's editorial calendar, blog, social content, and thought leadership output. You will develop content that educates prospective franchisees, builds brand authority, and drives organic growth.",
    responsibilities: [
      'Develop and execute a comprehensive content strategy across channels',
      'Write and edit long-form blog posts, guides, and case studies',
      'Manage the editorial calendar and content production pipeline',
      'Collaborate with SEO, design, and growth teams on content campaigns',
      'Analyze content performance and optimize based on data',
      'Develop brand voice guidelines and ensure consistency',
    ],
    requirements: [
      '2+ years of content strategy or editorial experience',
      'Exceptional writing and editing skills in English',
      'Understanding of SEO principles and content marketing',
      'Experience with CMS platforms and analytics tools',
      'Knowledge of the franchise or business ecosystem is a plus',
    ],
  },
  {
    id: 'business-development-lead',
    title: 'Business Development Lead',
    dept: 'Sales',
    type: 'Full Time',
    mode: 'Hybrid',
    location: 'Mumbai / Bangalore',
    salary: '₹8L – ₹12L / yr',
    tagline: 'Own the revenue pipeline and build strategic partnerships for iFranchise.',
    reportsTo: 'Head of Revenue',
    experience: '4+ Years',
    openings: '2',
    joining: 'Immediate',
    rounds: '3 Rounds',
    whyJoin: "You'll be closing deals that directly shape the iFranchise brand portfolio. With direct access to founders and a fast-moving pipeline, this role offers the kind of ownership and impact that most BD roles never provide.",
    about: "The Business Development Lead will drive iFranchise's revenue growth by identifying new business opportunities, closing strategic partnerships, and expanding our network of franchise brands and investors. You will work directly with the founding team.",
    responsibilities: [
      'Identify, qualify, and close new business opportunities',
      'Build and manage a pipeline of franchise brand and investor partnerships',
      'Develop proposals, pitch decks, and partnership agreements',
      'Represent iFranchise at industry events and franchise expos',
      'Collaborate with marketing on demand generation strategies',
      'Report on revenue metrics and pipeline health to leadership',
    ],
    requirements: [
      '4+ years in business development, sales, or strategic partnerships',
      'Proven track record of closing deals and exceeding targets',
      'Strong network in the franchise, retail, or startup ecosystem',
      'Excellent communication, negotiation, and presentation skills',
      'Self-starter with high ownership and accountability',
    ],
  },
];
